import type { Metadata } from 'next';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import Header from '@/components/common/Header';
import Providers from '@/providers/providers';
import '@/css/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Providers>
          <Header />

          <main className="mx-auto my-8 w-full max-w-6xl">
            <ReactQueryDevtools />
            {children}
          </main>
        </Providers>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
